#!/bin/bash
if [ $# -ne 3 ]
then
echo "You have not provided three arguments"
exit 1
fi
n1=$1
n2=$2
n3=$3


if [ $n1 -gt $n2  ] && [ $n1 -gt $n3 ]
then 
echo "$n1 is biggest number "
elif [ $n2 -gt $n1 ] && [ $n2 -gt $n3 ]
then 
echo " $n2 is biggest number "
