#! /bin/bash

#Shell Script to print Fibonacci series 

echo "Enter the value of n for "
read n
a=0
b=1
count=2
echo "Fibonacci Series"
echo $a
echo $b

while [ $count -le $n ]
do
fib=`expr $a + $b`
a=$b
b=$fib
echo $fib
count=`expr $count + 1`
done